---
title: "Simulating Blackjack"
author: "Group 162: David Claszen"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0em}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


# Abstract




# Background and Description of Problem

## Background

Blackjack is a well-known casino card game with around 2 to 7 players using one or multiple 52 card decks. Each round, the players place an initial bet and are then each dealt 2 cards by the dealer. The dealer deals him/herself two cards as well, the first of which face-up and the second face down (the hole card). The goal is to win money by creating hands of cards with a value higher than the dealer's hand but not exceeding 21, which counts as a loss or bust. Each player gets to decide whether to "hit" and get another card, to "double" their bet and get one final card and finish, to "split" their current hand into two new hands (requiring another bet as well), or to "stand" and finish their turn with their current hand. After the players have finished their hands, the dealer draws until their hand achieves a total of 17 or higher, but never doubles or splits. If the dealer busts, all players that didn't bust, win an amount equal to their bet, but players who already went bust lose anyway. If the player and dealer tie (a "push"), the bet is returned.

All cards with a numerical value (2 to 10) are worth as many points as their number. All face cards (kings, queens, etc.) are worth 10 points. An ace can be worth either 1 or 11 points depending on whether counting it as 11 would push the total beyond 21 or not. A natural happens when an initial hand consists of an ace and a face card, totaling 21. If only the player holds a natural, he receives 1.5 times his original bet. If both hold a natural, it is another push and the bet is returned. One mayor rule variation is whether the dealer has to hit or stand on a soft 17. A soft hand is a hand with an ace that can be counted as 11 without the total exceeding 21; that is, if more cards are drawn and the total with an ace of 11 exceeds 21, it can still be counted as a 1 instead. Standing on soft 17 is commonly referred to as S17 and having to hit as H17. 

Mathematically, there has already been an optimal strategy for blackjack since Baldwin *et al.*'s 1956 paper, "The Optimum Strategy in Blackjack". According to Baldwin *et al.*, this would result in an overall mathematical expectation of -0.006.^[Baldwin, Roger R., Wilbert E. Cantey, Herbert Maisel, and James P. McDermott. “The Optimum Strategy in Blackjack.” *Journal of the American Statistical Association* 51, no. 275 (1956): 429–439: 439.] This strategy, and minor variations on it, have become commonly known as the basic strategy, popularized by Edward O. Thorp's *Beat the Dealer*. Baldwin did not take into account the conditional expectation of a hand given the cards that were already played since the last shuffle, which essentially meant that blackjack hands were not independent of each other. Thorp's improvements of the basic strategy use card counting methods to incorporate this fact. 


Practically, it can be memorized, but it is more often printed on three cards showing what to do for each combination of the player's hand value and dealer's face card (one for hard totals, soft totals, and hands which can be split). 


Simpler versions often consist of rules build from this basic strategy that are easier to remember. Thorp builds further on top of this basic strategy 


## Description of Problem

The main question
The main question is: are there blackjack strategies that are practical and profitable? 
A strategy that is profitable but impossible to execute would still not be very helpful. 
This would seem to put a rather early dent into the question w

In increasing order of complexity (or decreasing practicality), the strategies that are tested are as follows. First, we simply mirror the dealer strategy of hitting until the hand reaches a value of 17. The expected value of this strategy is known and simulating this serves as a decent validation to test whether the model performs as it should. We use the dealer variation of having to hit a soft 17 (H17) because this is a more common rule variation in American casino's. Second, we use a strategy that consists of some easy to remember rules. These rules are a simplified version of the third and final strategy that is simulated, namely the basic strategy mentioned earlier.


# Code

## Simulating a Game

In broad strokes, the code does the following. N-number of decks are initialized and shuffled. `play_game` calls on all other required functions so as to simulate one game of blackjack. If the game to be played is fresh and not the result from a split, it deals 2 cards to the dealer, creates as many players as requested, places their initial bets, and deals them 2 cards using `deal_cards` which it takes and deletes from the global deck. Then, each player action is decided on through logical operators and look-up tables in the function `player_logic`. Each strategy consists of a set of three given look-up tables (one for hard totals, one for soft totals, and one for splits), where the recommended action is looked up from rows of player hand values and columns of dealer face card values. `player_actions` executes the taken action: either to stand, hit, double, or split. The resulting hand then goes back to `play_game`. If the player didn't go bust already, `dealer_logic` runs through the fixed rules for a dealer to determine their final hand. Based on that value, and the final player hand, the outcome is determined and returned. In the case of a split, the hand is split into two new hands, and each hand is given an additional card within `player_actions`. Together with the existing dealer hand, these two hands are send back to the `play_game` function to determine their outcome. There is also a manual option to play some games of blackjack against the computer based on your input actions. This wasn't the focus of this project and hasn't been tested thoroughly, but it works well enough.

## Improvements

Currently, using multiple players works largely as it should, except for when a player splits. The way this is dealt with means that those two split hands go off on their own, play a game with their dealer, record their results, and then the other players continue. This can mean that the dealer will most likely draw different cards to determine the outcome of those split games compared to the games of the other players. This isn't a problem for the simulations below because those will only consider a single player. 



## Simulating Many Games


R's random number generator uses the Mersenne Twister algorithm. To ensure that the results of the code are reproducible, the function must be given a seed value. Although it is overkill given the period of the Mersenne Twister, each replication of the simulation increments the seed by one to create independent replications. 



















